---
- name: Ensure AIDE package is installed
  package:
    name: aide
    state: present

- name: Configure aide.conf
  ansible.builtin.copy:
    src: files/aide.conf.j2
    dest: /etc/aide.conf
    
- name: Initialize AIDE database
  command: aide --init
  
- name: start using aide database
  command: "mv /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz"

        
  # output will be written to /var/log/aide/aide.log as stated in aide.conf
- name: Create cronjob for aide check once a day
  ansible.builtin.cron:
    name: "Run aide check"
    minute: "0"
    hour: {{aide_cron_hour}}
    weekday: {{aide_cron_weekday}}
    job: "aide --check"
  
