---
- name: Ensure Auditd package is installed
  package:
    name: audit
    state: present  

- name: Start Auditd service
  service:
    name: auditd
    state: started
    enabled: yes
    
- name: Copy audit.rules
  ansible.builtin.copy:
    src: files/audit.rules
    dest: /etc/audit/audit.rules
