---
- name: Install firewalld
  ansible.builtin.package:
    name: firewalld
    state: present
      
- name: Start and enable firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: yes
- name: set log denied to all
  command: firewall-cmd --set-log-denied=all
